export const hexColor: Record<string, { hexColor: string }> = {
  Black: { hexColor: "#262326" },
  "Off-White": { hexColor: "#efeee5" },
  "Navy Blue": { hexColor: "#272a41" },
  Red: { hexColor: "#d92348" },
  "Twilight Black": { hexColor: "#1a1a1a" },
  "Grey Marl": { hexColor: "#c5c7c9" },
  "Moss Green": { hexColor: "#b3b6a9" },
  "Scarab Teal": { hexColor: "#048885" },
  "Rind Yellow": { hexColor: "#f3e7cb" },
  "Maitake Beige": { hexColor: "#e4ddc0" },
  "Atmosphere Grey": { hexColor: "#65666d" },
  "Summit Blue": { hexColor: "#7496c1" },
  Stone: { hexColor: "#c2bfb7" },
  "Raisin Purple": { hexColor: "#c7b5bf" },
  Sand: { hexColor: "#ecded3" },
  "Aster Purple": { hexColor: "#8691bb" },
  "Chestnut Brown": { hexColor: "#573631" },
  "Foliage Green": { hexColor: "#123434" },
  Taupe: { hexColor: "#9c8d7b" },
  "Eucalyptus Blue": { hexColor: "#bccfc6" },
  "Volcanic Grey": { hexColor: "#656062" }
};
